### ISSUE TITLE
new field to be added to settings

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#10]
could you please add "Order_emailed_to" to the settings with a value of "w.paton@gmail.com" and adjust your coding to send the order of the email to that variable.

**Comment by mrjeggles** [comment]
which raises the question, when we go live how/where from do these emails get sent?

**Comment by yigitbacakoglu** [comment]
Yeah, which email do you want to use?

**Comment by mrjeggles** [comment]
I think SendGrid add on should do the job, they certainly won't get 400 orders a day so the free account will be sufficient. I have had no experience with this, what is your suggestion?

**Comment by yigitbacakoglu** [comment]
We need an email address first to use. For example currently we use 'projects@yigitbacakoglu.com' which uses yandex.com as smtp server.

So, you will need to provide an email address and its smtp settings.

Our current setting:

ActionMailer::Base.smtp_settings = {
    :address => "smtp.yandex.ru",
    :port => 587,
    :user_name => "projects@yigitbacakoglu.com",
    :password => "secret_pass",
    :authentication => :plain,
    :enable_starttls_auto => true,
    :host => "yigitbacakoglu.com"

}

**Comment by mrjeggles** [comment]
thanks , I'll get one organized.

On Sun, Feb 1, 2015 at 10:01 PM, Yigit C. Bacakoglu <
notifications@github.com> wrote:

> We need an email address first to use. For example currently we use '
> projects@yigitbacakoglu.com' which uses yandex.com as smtp server.
>
> So, you will need to provide an email address and its smtp settings.
>
> Our current setting:
>
> ActionMailer::Base.smtp_settings = {
> :address => "smtp.yandex.ru",
> :port => 587,
> :user_name => "projects@yigitbacakoglu.com",
> :password => "secret_pass",
> :authentication => :plain,
> :enable_starttls_auto => true,
> :host => "yigitbacakoglu.com"
>
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ycbTR/sample/issues/10#issuecomment-72360286>.
>



-- 
Warwick Paton
Computer Operating Services.
Ph: 57981435
Mob: 0401967888

**Comment by mrjeggles** [comment]
Hi Yigit 
I've set up gmail account
EMAIL_HOST='smtp.gmail.com'

EMAIL_PORT='587'

EMAIL_DOMAIN= 'gmail.com'

EMAIL_USER_NAME='dookieseedbank@gmail.com'

EMAIL_PASSWORD=  will email to you as this repository is open to anyone.
