### ISSUE TITLE
public order generated twice

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#11]
•	Put a Nursery order through from Public Catalogue and it was generated twice N0057 and N0058 Haven’t tried to duplicate it yet.
 	 
![image](https://cloud.githubusercontent.com/assets/10021224/5953911/383c53c0-a7e4-11e4-86d6-f3962e39cf8b.png)

**Comment by yigitbacakoglu** [comment]
Probably you clicked 2 times. I added a workaround to prevent this issue.
