### ISSUE TITLE
Form not picking up Order Number

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#12]
•	On both Direct Seeding and Nursery orders we need the order number to come through to the “Show Form” details http://seedbank-ycbtr.herokuapp.com/customer/orders/S0052

 
![image](https://cloud.githubusercontent.com/assets/10021224/5953944/cb445a82-a7e4-11e4-8197-b567d5ade872.png)

**Comment by yigitbacakoglu** [comment]
Where do you want to see the order number?

**Comment by mrjeggles** [comment]
it is the SB no field on the form eg N0061 or S0060

**Comment by yigitbacakoglu** [comment]
Why we need that field? We are already showing order number in print views

**Comment by mrjeggles** [comment]
Yeah OK but in that case we should remove "SB no" from the body of the form.
