### ISSUE TITLE
Staff need access to order forms

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#14]
•	Staff need to be able to edit these forms http://seedbank-ycbtr.herokuapp.com/admin/orders/58/edit#selectModal  – and create them when entering an order for a customer

**Comment by yigitbacakoglu** [comment]
I was thinking to keep 'Order Form' as original. So when customer creates a form, it remains forever as original.

An order is auto generated according to that form and staff can edit "that order" as he wish. 

So, can you explain why staff may want to edit the 'order form'. Btw, editing only info is not a problem but if you want to edit items as well, it will be a big problem in terms of data consistency.

If you want, I can generate another view which combines 'Order form's' info (except item selection), and current order's line items for printing. (ref #13)

**Comment by mrjeggles** [comment]
the "order form" may need editing if for instance some information was not entered by the customer. eg they may have left out the postal address.

**Comment by mrjeggles** [comment]
sorry I didn't pick up that       Nursery Order Form (Edit) was a link to edit.
