### ISSUE TITLE
SPA Populations

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#19]
1.	SPA Populations  – species, heritage lotnumber(s) and region(s) provenance(s) and location(s)
	similar to “mock up of SPA populations.xlsx” generated from lotnumber, FDS, and Plant 
 	for each row in lotnumber table where spa_name contains “SPA”
 		retrieve Species from FDS for lotnumber
 		retrieve from each heritage lotnumber the  region provenance and location

**Comment by yigitbacakoglu** [comment]
Couldn't understand...

![image](https://cloud.githubusercontent.com/assets/1568948/6134583/2173b99a-b16b-11e4-8bf5-097f2185b0c9.png)


- 9968 is the "Lot number-A" where spa_name field is not blank.
- The first species in the first row comes from "Lot number-A" 's last FDS.
But where "6923/07" heritage value comes from ? 

What is the difference of it from other lines below?

**Comment by mrjeggles** [comment]
Hi Yigit,
6923/07 is fictitious, Well it is a real lot number but not connected at the moment to a FDS as they haven't got all their data entered yet. I am just emphasizing that the lotnumber in a SPA can have multiple heritages. i.e it can be collected from various regions, provenances and locations, all mixed together and planted in the SPA. This report is needed to show where it has originally come from.
Not all lotnumbers in the SPA will have multiple heritages. 9971 represents one that has only one heritage.
So this mock up demos a SPA with 2 lot numbers - one with 3 heritages and one with one.
Of course theoretically a SPA report could contain many lotnumbers and be quite a few pages.
Hope this explains this
Warwick

**Comment by yigitbacakoglu** [comment]
Still I don't understand.
Why 6923/07 is at the first line (same line with lot number), and others at bottom? It looks like, something is special with that heritage number.

Please make good abstraction to prevent confusions.

**Comment by mrjeggles** [comment]
believe me I'm trying :)

Hope this attachment is a clearer representation. only fictitious values.

For every lotnumber in each SPA.

each SPA can have many Lotnumbers which in turn can have many heritages,
the "Heritage Lotnumber" providing the Region Provenance and Location.

Please excuse my difficulty, I'm not doing it on purpose!
cheers
Warwick

On Wed, Feb 11, 2015 at 7:14 PM, Yigit C. Bacakoglu <
notifications@github.com> wrote:

> Still I don't understand.
> Why 6923/07 is at the first line (same line with lot number), and others
> at bottom? It looks like, something is special with that heritage number.
>
> Please make good abstraction to prevent confusions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ycbTR/sample/issues/19#issuecomment-73846125>.
>



-- 
Warwick Paton
Computer Operating Services.
Ph: 57981435
Mob: 0401967888
