### ISSUE TITLE
Seeds on Hold

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#25]
details to come

**Comment by mrjeggles** [comment]
Seeds on Hold, example “mock up of Seeds on hold.xlsx”
extracted from FDS with qty_onhold > 0
list Collector, lotnumber, species, date, qty_onhold, comments and all adjustment transactions linked to that FDS 
grouped by Collector and sorted by date within the group

**Comment by yigitbacakoglu** [comment]
You wrote this:
![image](https://cloud.githubusercontent.com/assets/1568948/6134759/432bbeb0-b16c-11e4-879e-6df7c3c8bd33.png)

But put information from parent FDS.
![image](https://cloud.githubusercontent.com/assets/1568948/6134775/52b63f0e-b16c-11e4-8750-12cab49b1924.png)

I am really having difficulties to understand what you exactly need. I can't see consistency in the excel files. Those are not doable for now. @mrjeggles

**Comment by mrjeggles** [comment]
ok I will go through it tomorrow and try and re express it.

**Comment by mrjeggles** [comment]
The purpose of this report is to show any seed that is “on hold” – so that staff can see the current state of it.
So we are only interested in lotnumbers where the original FDS has a value in “qty_onhold”. so the subset of FDS is Qty_onhold > 0.
 It may be on_hold for quite some time. For instance a stocktake may reveal that some of it is damaged (weavels eaten it or something) and therefore the qty_on hold has to be adjusted. Or some of it may have been “borrowed” for another order so there will be an adjustment associated with it.
So to see the current state we need to show the original Qty_onhold and all the adjustment transactions associated with the original FDS. Though the qty_bank and qty_consigned may not be relevant ( staff decide that when they look at it) the qty_onhold definitely is.

sending "retry of mockup of seeds on hold"

**Comment by mrjeggles** [comment]
Hi Yigit,
hope this makes more sense to you.
have added comment on github.
cheers
Warwick

On Wed, Feb 11, 2015 at 6:34 AM, Yigit C. Bacakoglu <
notifications@github.com> wrote:

> You wrote this:
> [image: image]
> <https://cloud.githubusercontent.com/assets/1568948/6134759/432bbeb0-b16c-11e4-879e-6df7c3c8bd33.png>
>
> But put information from parent FDS.
> [image: image]
> <https://cloud.githubusercontent.com/assets/1568948/6134775/52b63f0e-b16c-11e4-8750-12cab49b1924.png>
>
> I am really having difficulties to understand what you exactly need. I
> can't see consistency in the excel files. Those are not doable for now.
> @mrjeggles <https://github.com/mrjeggles>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ycbTR/sample/issues/25#issuecomment-73767243>.
>



-- 
Warwick Paton
Computer Operating Services.
Ph: 57981435
Mob: 0401967888

**Comment by yigitbacakoglu** [comment]
Hi Warwick, 

I didn't receive "retry of mockup of seeds on hold" file

**Comment by mrjeggles** [comment]
Hi Yigit,
I can't work out how to send email from Github - so I emailed you the attachment by replying to ycbTR/sample <reply+0098e968745a95c83a98770e2bed2446a5da10adca883f1892cf0000000110f7246792a169ce035476c4@reply.github.com>
not sure how to get it to you if that doesn't get through.
I'll send it again via freelancer.

**Comment by mrjeggles** [comment]
hmm I see the cut and paste didn't work in the above comment either.
ok so please check Freelancer.
Warwick
