### ISSUE TITLE
Ipad not giving full functionality

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#32]
On the iPad, (both Safari and Google Chrome browsers) staff cannot access the Catalog sub menu (from management). Touching the < brings up the orders page (http://seedbank-ycbtr.herokuapp.com/admin/orders ) Also cannot scroll down to get the full list of management menu. and therefore cannot log out. The page behind the menu (.../admin/orders) scrolls
Is this something you can control? Or is there a workaround?

**Comment by yigitbacakoglu** [comment]
Can I extract and add catalogue menu to navbar?

**Comment by mrjeggles** [comment]
yes I think that will be ok, Can you please give me a look at it so I can decide?

**Comment by mrjeggles** [comment]
yes that's fine, thank you very much

**Comment by mrjeggles** [comment]
ps. How do i add label to my comments? I've looked on web and asked a collegue but I can't get an answer :)

**Comment by yigitbacakoglu** [comment]
Click on 'Labels' link :)
https://www.dropbox.com/s/k1coxb6006yxh34/Screenshot%202015-02-06%2010.25.05.png?dl=0

**Comment by mrjeggles** [comment]
I have nothing to click on

![screenshot from 2015-02-06 21 28 58](https://cloud.githubusercontent.com/assets/10021224/6077892/bc95ca3e-ae47-11e4-89b8-d24bd4166256.png)

**Comment by yigitbacakoglu** [comment]
Ok, now you should have related links
