### ISSUE TITLE
feedback on SPA Populations report.

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#37]
Hi Yigit,
from what I can check (not much heritage data yet) this report is working fine. Thanks for your patience and persistence.
but here is the catch - there is always a catch :)
Is it possible to sort SPA names alphabetically  then by lotno then by Region then by Provenance please. I have sorted XL sheet bySPA name and then lotno to give you the gist of it, but not Region and Provenance. I have sent this via Freelancer. (spa populations feedback.xlsx)

There will be some lotnumbers in the spa where the seed was collected from the spa itself. That is the spa had an existing population. And this is the only sample in SPA. It seems to me that we could report the Species, Heritage, Region, Provenance, and Location if the Heritage Lotnumber could be the same as the parent lotnumber. At the moment when entering the lotnumber details that lotnumber is excluded from the dropdown for heritage. Can that done or is there some relationship that I can't see that prevents it? See comments on lines 49 and 50 on spreadsheet  (spa populations feedback.xlsx) I will make this a separate issue.

**Comment by yigitbacakoglu** [comment]
I can add 'self_heritage' field for that, does it work?

**Comment by mrjeggles** [comment]
yes seems like self heritage does what we want 
thanks
