### ISSUE TITLE
lotnumbers - heritage no able to be same as parent lotnumber?

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#38]
There will be some lotnumbers in the spa where the seed was collected from the spa itself. That is the spa had an existing population. And this is the only sample in SPA. It seems to me that we could report the Species, Heritage, Region, Provenance, and Location if the Heritage Lotnumber could be the same as the parent lotnumber. At the moment when entering the lotnumber details that lotnumber is excluded from the dropdown for heritage. Can that done or is there some relationship that I can't see that prevents it? See comments on lines 49 and 50 on spreadsheet  (spa populations feedback.xlsx)

**Comment by yigitbacakoglu** [comment]
ref #37 

I can add 'self_heritage' field for that, does it work?
