### ISSUE TITLE
Add service regions settings for catalog header

### ISSUE THREAD

**Issue by yigitbacakoglu** [ycbTR/sample#4]

**Comment by mrjeggles** [comment]
Move the regions up so they are together on consecutive lines 2 - 7
B - Broadford J - Jamieson MD - Mt Disappointment S-W - Seymour - Whitehead Crk
EN - Euroa - Nagambie L - Lurg PW - Plains West W&C - Warbys & Chesneys
GG - Ghin Ghin M - Mansfield P - Pyalong Y – Yea
D - Dookie K-E - Koonda - Earlston PN - Plains North T – Tatong
A - Alexandra HC - Hughes Creek Ma - Marysville R – Rushworth
C - Costerfield K-B - Killawarra - Boweya PE - Plains East S – Strathbogies 
A bit confusing. Each of those have inline HTML codes, which make bold abbr. Staff will see meaningless HTML codes while editing that setting.

sorry that request wasn't clear. We don't need the regions editable by the staff, its for appearance only to get them all together into a visual group.

**Comment by mrjeggles** [comment]
bonza!
