### ISSUE TITLE
Additional field Seed Sales Reports

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#41]
To the Seed Sales Reports (Nursery and Direct Seeding) can we please add the column “email address” between Postal Address and Quantity. ie customer email address.

**Comment by mrjeggles** [comment]
the email address is not coming through to the report

**Comment by yigitbacakoglu** [comment]
Which email address?

**Comment by yigitbacakoglu** [comment]
If user has email address, then I add that info.

**Comment by mrjeggles** [comment]
customer email needs to come through as per screenshots
![customer email](https://cloud.githubusercontent.com/assets/10021224/6704014/4b7775ae-cd97-11e4-8e80-c981df34fc07.JPG)
![customer email not coming through](https://cloud.githubusercontent.com/assets/10021224/6704015/4b7a8b04-cd97-11e4-8bf3-763f2e258294.JPG)
