### ISSUE TITLE
some plants not showing in direct seeding ordering

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#48]
These plants are not always showing up on the Direct Seeding order form,   Acacia acinacea, Acacia genistifolia, Dodonaea viscosa cuneata, Acacia verniciflua, Acacia pycnantha, Acacia implexa.

the staff say they "show sometimes", I can't see them when I do an order at the moment.

**Comment by yigitbacakoglu** [comment]
For Direct Seeding:

Plant must be 'direct_seedable' and Lot Number's 'spa_specific' column must be 'False' or 'Null'

**Comment by mrjeggles** [comment]
just want plant to be 'direct_seedable' , no filtering on the Lot Number's 'spa_specific' column
