### ISSUE TITLE
Fix timezone issue

### ISSUE THREAD

**Issue by yigitbacakoglu** [ycbTR/sample#5]

**Comment by mrjeggles** [comment]
this is starting to become a bit of an issue now as data is being entered. Have you had a chance to think about it? If we can't solve it are there any work arounds that we may consider?

**Comment by yigitbacakoglu** [comment]
ok, fixed it.

**Comment by mrjeggles** [comment]
great, well done and thank you.

On Sun, Feb 1, 2015 at 9:52 PM, Yigit C. Bacakoglu <notifications@github.com
> wrote:

> Closed #5 <https://github.com/ycbTR/sample/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ycbTR/sample/issues/5#event-228115662>.
>



-- 
Warwick Paton
Computer Operating Services.
Ph: 57981435
Mob: 0401967888
