### ISSUE TITLE
customers need to be unique

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#51]
see explanation sent via freelancer attachment

**Comment by mrjeggles** [comment]
this is still allowing me to put the same customer in again.
eg I have just entered Gorden Norris

**Comment by yigitbacakoglu** [comment]
what is the uniqueness criteria for a customer? should name or lastname or name & lastname be unique?

**Comment by mrjeggles** [comment]
"name & lastname" (ie concatonated) to be unique
