### ISSUE TITLE
Direct Seeding form showing wrong defaults for new customer

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#55]
I have been able to generate this twice by following these steps BUT IT DOES NOT HAPPEN when I login as me (w.paton@gmail.com, pw seedbank)
1. login as seedbank@gvce.com.au pw "seedbank"
2. new order
3. use existing = NO
4. add new customer - first name, last name, address 1, town, postcode, phone
5. Direct Seeding
6. Form shows Susan Sleigh details - should be blank

**Comment by yigitbacakoglu** [comment]
it must work now. 

Also if you need to change customer while editing an order, you should also change the customer of the related order form.
