### ISSUE TITLE
unique customer modification breaks the app

### ISSUE THREAD

**Issue by mrjeggles** [ycbTR/sample#61]
Hi Yigit, 
I've been trying not to disturb you but we have a malfunction here that we need to get fixed. The fix of issue 51 has broken the system. 
this is happening even when the customer is unique and even if we add a new customer they cant be used.
Hope you can manage to get a look at this asap.
thanks 
Warwick

![image](https://cloud.githubusercontent.com/assets/10021224/9572164/e39e651c-4fed-11e5-975f-ef876dc4b38a.png)

**Comment by yigitbacakoglu** [comment]
fixed
