### ISSUE TITLE
Heritage of a Heritage

### ISSUE THREAD

**Issue by yigitbacakoglu** [ycbTR/sample#7]
Need to show heritage history of a lot number

**Comment by mrjeggles** [comment]
8.	Heritage of a Heritage. 
The cases of SPA’s - the lot numbers have heritage values; it can occur that this heritage LotNumber also has a heritage number and so on. They need to see for example 18546/8827..7940..6623/8852 where 8827,8852 are heritage of 18546 and 7940 and 6623 are heritage of 8827. This is a simple example – it could be a bit more convoluted than this. We need be able to query this and as well as display on screen dump to XL for a printout. In which page do you need this? Please write down use case flow. (Lot Numbers > Click Heritage History > Modal appears with history > Click Excel link > Downloads heritage history)

We will put this one in Reports. more details to come.

**Comment by mrjeggles** [comment]
I think I have this covered in SPA Populations report (#19)
